Azure/azure-sdk-for-ios

AzureCore/AzureCore.xcodeproj/project.pbxproj, AzureCore/Cartfile, AzureCore/Cartfile.resolved
Fixes #3.
- Add [KeychainAccess](https://github.com/kishikawakatsumi/KeychainAccess) dependency for Secure Storage
=> Add KeychainAccess dependency

AzureData/README.md, AzureData/Source/AzureData.swift, AzureData/Source/DocumentClient.swift, AzureData/Source/Resources/ResourceOracle.swift, AzureData/Tests/DatabaseTests.swift
Fixes #31 .
- Add database deletion API functions
- Update the docs
=> Add database deletion API functions

AzureData/README.md, AzureData/Source/AzureData.swift, AzureData/Source/AzureDataExtensions.swift, AzureData/Source/DocumentClient.swift, AzureData/Tests/DocumentCollectionTests.swift
Fixes #32 .
- Add collection deletion functions
- Update README
=> Add collection deletion API functions

AzureData/README.md, AzureData/Source/AzureData.swift, AzureData/Source/AzureDataExtensions.swift
Fixes #39  .
- Add missing API functions
- Update the docs
=> #39 Update User API

AzureData/Source/AzureDataExtensions.swift, AzureData/Tests/PermissionTests.swift
Fixes #60.
- Add the `refresh` extension function to `Permission`
=> Add refresh to Permission

AzureData/AzureData.xcodeproj/project.pbxproj, AzureData/Source/AzureData.swift, AzureData/Source/AzureDataExtensions.swift, AzureData/Source/DocumentClient.swift, AzureData/Source/DocumentClientError.swift, AzureData/Source/MSHttpHeader.swift, AzureData/Source/Query.swift, AzureData/Source/ResourceLocation.swift, AzureData/Source/Resources/CodableResources.swift, AzureData/Source/Resources/ResourceRequestError.swift, AzureData/Source/Resources/Resources.swift, AzureData/Source/Response.swift, AzureData/Source/UtilityExtensions.swift, AzureData/Tests/DocumentTests.swift, AzureData/Tests/Extensions.swift, AzureData/Tests/StoredProcedureTests.swift, AzureData/Tests/UserDefinedFunctionTests.swift
Fixes #21.
- Add pagination support to list requests
- Add pagination support to query requests
- Add tests
=> Implement pagination for query and read-feed results

AzureData/Source/AzureData.swift, AzureData/Source/DocumentClient.swift, AzureData/Source/MSHttpHeader.swift, AzureData/Tests/DocumentTests.swift
Fixes #29.
- Add createOrReplace API for documents
=> Add createOrReplace API for documents

AzureData/README.md, AzureData/Source/AzureData.swift, AzureData/Source/AzureDataExtensions.swift, AzureData/Source/DocumentClient.swift, AzureData/Tests/AzureDataTests.swift, AzureData/Tests/CollectionDocumentExtensionsTests.swift, AzureData/Tests/DocumentTests.swift, AzureData/Tests/ExamplePermissionProviderTests.swift, AzureData/Tests/PermissionTests.swift
- Update the docs
- Rename some parameters for consistency
=> Update docs and rename some parameters for consistency

AzureData/AzureData.xcodeproj/project.pbxproj, AzureData/Source/AzureData.swift, AzureData/Source/ResourceCache.swift, AzureData/Source/ResourceEncryptor.swift
Fixes #72.
- Allow users to implement custom data encryption
=> Custom data encryption

.gitignore, AzureCore/AzureCore.xcodeproj/project.pbxproj, AzureCore/Source/Azure.plist, AzureCore/Source/AzureKeys.swift, AzureCore/Source/AzureTests.plist, AzureData/README.md, AzureData/Source/AzureData.swift, AzureData/Source/DocumentClient.swift, AzureData/Tests/AzureDataTests.swift
- Add the option to provide the Azure account name and master key using property lists.
=> Configure AzureData from plists

AzureData/README.md
Fixes #78.
- Document the usage of ResourceEncryptor in AzureData's README
=> Document the usage of ResourceEncryptor

AzureData/Source/DocumentClient.swift, AzureData/Source/ResourceCache.swift, AzureData/Source/ResourceOracle.swift, AzureData/Source/Response.swift, AzureData/Source/UtilityExtensions.swift
Fixes #75.
- Paginate `get` responses while offline
=> Add support for resources pagination while offline

AzureData/Source/UtilityExtensions.swift
Fixes #90.
- Fix a crash on empty URLs
=> Fix crash on empty URL

AzureData/Source/ResourceCache.swift, AzureData/Source/ResourceLocation.swift, AzureData/Source/ResourceWriteOperationQueue.swift, AzureData/Source/UtilityExtensions.swift, Example/AzureData iOS Example/AzureData iOS Example/CollectionTableViewController.swift, Example/AzureData iOS Example/AzureData iOS Example/DatabaseTableViewController.swift, Example/AzureData iOS Example/AzureData iOS Example/DocumentTableViewController.swift, Example/AzureData iOS Example/AzureData iOS Example/PermissionTableViewController.swift, Example/AzureData iOS Example/AzureData iOS Example/StoredProcedureTableViewController.swift, Example/AzureData iOS Example/AzureData iOS Example/TriggerTableViewController.swift, Example/AzureData iOS Example/AzureData iOS Example/UserDefinedFunctionTableViewController.swift
Fixes a few bugs related to the offline capabilities.
- Fix a bug where offline resources were saved in the wrong directory
- Fix a bug where a crash occurs when an offline resource is created as a child of another offline resource. The bug occured when the process creating the child resource is different from the process that created the parent resource.
- Fix a bug where pending offline writes were not always processed once the network becomes reachable
- Update the sample app to automatically refresh when the offline queue is fully synced
=> Fix offline capabilities bugs

AzureData/AzureData.xcodeproj/project.pbxproj, AzureData/Source/DocumentClient.swift, AzureData/Source/Geometry/Point.swift, AzureData/Source/Geometry/Query+Geometry.swift, AzureData/Source/Query.swift, AzureData/Source/ResourceCache.swift, AzureData/Tests/DocumentTests.swift, AzureData/Tests/PointTests.swift, AzureData/Tests/_AzureDataTests.swift
- Add offline persistence support to the Query API
- Add support for spatial queries on Point
=> Add offline and geometry support to the Query API

.travis.yml
- Update Xcode to the `10.2` version on Travis
=> Update osx_image version

AzureAppConfiguration/Source/AppConfigurationClient.swift, AzureAppConfiguration/Source/Credentials/AppConfigurationClientCredentials.swift, AzureCore/AzureCore.xcodeproj/project.pbxproj, AzureCore/Source/ClientLogger.swift, AzureCore/Source/Collections/Collections.swift, AzureCore/Source/Implementation/Transport/UrlSessionTransport.swift, AzureCore/Source/Pipeline/PipelineBase.swift, AzureCore/Source/Pipeline/PipelineClient.swift, AzureCore/Source/Pipeline/PipelineError.swift, AzureCore/Source/Pipeline/PipelineLogger.swift, AzureCore/Source/Pipeline/PipelineRequest.swift, AzureCore/Source/Pipeline/PipelineResponse.swift, AzureCore/Source/Pipeline/Policies/ContentDecodePolicy.swift, AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift, AzureCore/Source/Pipeline/Transport/HttpHeader.swift, AzureCore/Source/Pipeline/Transport/HttpMessage.swift, AzureCore/Source/Pipeline/Transport/HttpRequest.swift, AzureCore/Source/Pipeline/Transport/HttpResponse.swift, AzureCore/Source/Util/RegexUtil.swift, AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/project.pbxproj, AzureStorageBlob/Source/StorageBlobClient.swift
Adds a logging framework and some pipeline logging policies.
Fixes #149
=> Logging policy

AzureAppConfiguration/AzureAppConfiguration.xcodeproj/project.pbxproj, AzureCSComputerVision/AzureCSComputerVision.xcodeproj/project.pbxproj, AzureCSTextAnalytics/AzureCSTextAnalytics.xcodeproj/project.pbxproj, AzureCore/AzureCore.xcodeproj/project.pbxproj, AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/project.pbxproj, AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj
Updates the version of Swift from 5 to 4, per guidelines discussion.
=> Change swift versions to Swift 4.0

AzureSDK.xcworkspace/xcshareddata/xcschemes/all.xcscheme, AzureSDK.xcworkspace/xcshareddata/xcschemes/appconfiguration.xcscheme, AzureSDK.xcworkspace/xcshareddata/xcschemes/cognitiveservices.xcscheme, AzureSDK.xcworkspace/xcshareddata/xcschemes/core.xcscheme, AzureSDK.xcworkspace/xcshareddata/xcschemes/examples.xcscheme, AzureSDK.xcworkspace/xcshareddata/xcschemes/storage.xcscheme, AzureSDK.xcworkspace/xcshareddata/xcschemes/textanalytics.xcscheme, examples/AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/xcshareddata/xcschemes/AzureSDKDemoSwift.xcscheme, sdk/appconfiguration/AzureAppConfiguration/AzureAppConfiguration.xcodeproj/project.pbxproj, sdk/appconfiguration/AzureAppConfiguration/AzureAppConfiguration.xcodeproj/xcshareddata/xcschemes/AzureAppConfiguration.xcscheme, sdk/cognitiveservices/AzureCSComputerVision/AzureCSComputerVision.xcodeproj/project.pbxproj, sdk/cognitiveservices/AzureCSComputerVision/AzureCSComputerVision.xcodeproj/xcshareddata/xcschemes/AzureCSComputerVision.xcscheme, sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj, sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/xcshareddata/xcschemes/AzureStorageBlob.xcscheme, sdk/textanalytics/AzureCSTextAnalytics/AzureCSTextAnalytics.xcodeproj/project.pbxproj, sdk/textanalytics/AzureCSTextAnalytics/AzureCSTextAnalytics.xcodeproj/xcshareddata/xcschemes/AzureCSTextAnalytics.xcscheme
Add working test targets with code coverage for all schemes
=> Test schemes

examples/AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/project.pbxproj, sdk/appconfiguration/AzureAppConfiguration/AzureAppConfiguration.xcodeproj/project.pbxproj, sdk/appconfiguration/AzureAppConfiguration/Source/Supporting Files/Info.plist, sdk/cognitiveservices/AzureCSComputerVision/AzureCSComputerVision.xcodeproj/project.pbxproj, sdk/cognitiveservices/AzureCSComputerVision/Source/Supporting Files/Info.plist, sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj, sdk/core/AzureCore/Source/Supporting Files/Info.plist, sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj, sdk/textanalytics/AzureCSTextAnalytics/AzureCSTextAnalytics.xcodeproj/project.pbxproj, sdk/textanalytics/AzureCSTextAnalytics/Source/Supporting Files/Info.plist
This PR sets the versions of the packages to ```1.0.0-beta.1``` across the board. We should discuss what the versions should actually be, but I needed to make sure the packages all had versions so that I could proceed with some scripting work.
=> Sets versions for packages (discuss?).

eng/.docsettings.yml, eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/pipelines/templates/variables/globals.yml
This PR will setup doc-warden to run against the READMEs in the repo.
=> Setup doc-warden to scan READMEs.

.swiftlint.yml, Package.swift, examples/AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/project.pbxproj, examples/AzureSDKDemoSwift/Source/Base.lproj/Main.storyboard, examples/AzureSDKDemoSwift/Source/BlobTableViewController.swift, examples/AzureSDKDemoSwift/Source/MainViewController.swift, sdk/appconfiguration/AzureAppConfiguration/AzureAppConfiguration.xcodeproj/project.pbxproj, sdk/cognitiveservices/AzureCSComputerVision/AzureCSComputerVision.xcodeproj/project.pbxproj, sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj, sdk/core/AzureCore/Source/Implementation/Transport/URLSessionTransport.swift, sdk/core/AzureCore/Source/Pipeline/Transport/HTTPRequest.swift, sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj, sdk/storage/AzureStorageBlob/Source/DataStructures/BlobSharedAccessSignature.swift, sdk/storage/AzureStorageBlob/Source/DataStructures/StorageStreamDownloader.swift, sdk/textanalytics/AzureCSTextAnalytics/AzureCSTextAnalytics.xcodeproj/project.pbxproj
Modifies the demo app, per discussions:
- immediately moves to the video container (skips selecting a container)
- adds pull-to-refresh capability for the video list
- adds upload button, which opens an image picker
Also, adds a `.swiftlint.yml` config file to temporarily disable certain Swiftlint rules. Addressing these violations is tracked by https://github.com/Azure/azure-sdk-for-ios/issues/198.
=> Update demo app.

.github/CODEOWNERS
This PR adds CODEOWNERS to the repo to be in line with our other repos.
=> Setup CODEOWNERS.

.jazzy/AzureAppConfiguration.yml, .jazzy/AzureCSComputerVision.yml, .jazzy/AzureCSTextAnalytics.yml, .jazzy/AzureCore.yml, .jazzy/AzureStorageBlob.yml, .jazzy/index.html.erb, CONTRIBUTING.md, README.md, Scripts/build_api_docs.sh, sdk/appconfiguration/AzureAppConfiguration/README.md, sdk/cognitiveservices/AzureCSComputerVision/README.md, sdk/core/AzureCore/README.md, sdk/storage/AzureStorageBlob/README.md, sdk/textanalytics/AzureCSTextAnalytics/README.md
Committing an initial pass at basic docs for iOS.
=> Prepare docs for publishing

examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift, examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift, sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj, sdk/core/AzureCore/Source/Util/StringUtil.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift, sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift, sdk/storage/AzureStorageBlob/Source/StorageStreamUploader.swift
Fixes issue with rehydrating transfers. Draft as I'm still investigating some CoreData issues that shouldn't be popping up.
Fixes #241.
=> Fix issues with local filesystem URLs.

sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift, sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift, sdk/storage/AzureStorageBlob/Source/StorageStreamUploader.swift
We need to resolve the local URL first, then read the file info.
=> Fix issue calculating the fileSize when uploading

sdk/storage/AzureStorageBlob/README.md, sdk/storage/AzureStorageBlob/Source/Credentials/StorageCredentials.swift
Also significantly expand documentation for authenticating the client
=> Add support for container / blob scoped SAS tokens

examples/AzureSDKDemoSwift/Source/Common.swift, sdk/storage/AzureStorageBlob/Source/Data/Transfer.swift, sdk/storage/AzureStorageBlob/Source/DataStructures/Enumerations.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift, sdk/storage/AzureStorageBlob/Source/TransferManager.swift, sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
Some API improvements that I worked on as I was writing the documentation.
=> Transfer api improvements

examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift, examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift, sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj, sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataClass.swift, sdk/storage/AzureStorageBlob/Source/DataStructures/LocalURL.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift, sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift, sdk/storage/AzureStorageBlob/Source/StorageStreamUploader.swift, sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
This was something I prototyped that allows the customer to use any well-known directory as the base for a local URL. Wanted to know what you thought.
=> Local urls proposal

sdk/core/AzureCore/Source/ClientLogger.swift, sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift, sdk/storage/AzureStorageBlob/Source/Util/StorageBlobClient+AllowLoggingValues.swift
=> Serialize logging

examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift, examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift, sdk/storage/AzureStorageBlob/Source/Data/AzureStorage.xcdatamodeld/AzureStorage.xcdatamodel/contents, sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataClass.swift, sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataProperties.swift, sdk/storage/AzureStorageBlob/Source/Data/Transfer.swift, sdk/storage/AzureStorageBlob/Source/Operation/BlobDownloadOperations.swift, sdk/storage/AzureStorageBlob/Source/Operation/BlockOperations.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift, sdk/storage/AzureStorageBlob/Source/TransferManager.swift, sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager+TransferDelegate.swift, sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
=> Update managed transfer progress reporting to use TransferProgress

examples/AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/xcshareddata/xcschemes/AzureSDKDemoSwift.xcscheme, examples/AzureSDKDemoSwift/Source/AppDelegate.swift, examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift, examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift, examples/AzureSDKDemoSwift/Source/Common.swift, sdk/storage/AzureStorageBlob/Source/Data/AzureStorage.xcdatamodeld/AzureStorage.xcdatamodel/contents, sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataClass.swift, sdk/storage/AzureStorageBlob/Source/DataStructures/Enumerations.swift, sdk/storage/AzureStorageBlob/Source/Operation/BlobDownloadOperations.swift, sdk/storage/AzureStorageBlob/Source/Operation/BlockOperations.swift, sdk/storage/AzureStorageBlob/Source/Operation/MultiBlobOperation.swift, sdk/storage/AzureStorageBlob/Source/Operation/TransferOperation.swift, sdk/storage/AzureStorageBlob/Source/Operation/TransferOperationQueue.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift, sdk/storage/AzureStorageBlob/Source/TransferManager.swift, sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager+TransferDelegate.swift, sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
Changes to improve the CoreData stability and performance, as well as some problems with the UI that were bogging down performance (and may have been responsible for some of the issues)
A transfer print-trace looks like:
```
RELOAD TABLE
1 didUpdate
RELOAD TABLE
Transfer 2279286792 didUpdateWithState: inProgress andProgress: 0.055555556
RELOAD TABLE
Transfer 2279286792 didUpdateWithState: inProgress andProgress: 0.11111111
RELOAD TABLE
Transfer 2279286792 didUpdateWithState: inProgress andProgress: 0.16666667
RELOAD TABLE
Transfer 2279286792 didUpdateWithState: inProgress andProgress: 0.22222222
RELOAD TABLE
Transfer 2279286792 didUpdateWithState: inProgress andProgress: 0.2777778
RELOAD TABLE
Transfer 2279286792 didUpdateWithState: inProgress andProgress: 0.33333334
RELOAD TABLE
Transfer …
```
=> CoreData improvements

sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
This PR simply removes a TODO, as #247 was fixed by the earlierPR #264.
=> Remove TODO. Close #247.

sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataClass.swift, sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataProperties.swift, sdk/storage/AzureStorageBlob/Source/Data/Transfer.swift, sdk/storage/AzureStorageBlob/Source/DataStructures/LocalURL.swift, sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift, sdk/storage/AzureStorageBlob/Source/TransferManager.swift, sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager+TransferDelegate.swift, sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
Resolve / hide confusing things from the docs:
- Remove client(withrestorationId) from transferdelegate
- Hide some things from the storage API docs
=> Docs improvements for the UX study

examples/AzureSDKDemoSwift/Source/AppDelegate.swift, examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift, examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift, examples/AzureSDKDemoSwift/Source/CustomTabBarController.swift, sdk/storage/AzureStorageBlob/Source/Operation/BlobDownloadOperations.swift
=> Fix single block blob download

examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift, examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift
=> Suppress warning for unused return value on upload/download

examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift, sdk/core/AzureCore/Source/Pipeline/Transport/HTTPHeader.swift, sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift
Closes #215.
Adds delete operation to the `BlobStorageClient` and to the demo app.
=> Add delete blob operation

examples/AzureSDKDemoSwift/Source/AppDelegate.swift, examples/AzureSDKDemoSwift/Source/Base.lproj/Main.storyboard, examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift, examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift, examples/AzureSDKDemoSwift/Source/Common.swift, examples/AzureSDKDemoSwift/Source/CustomTabBarController.swift, sdk/core/AzureCore/Source/Util/ReachabilityManager.swift, sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj, sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift, sdk/storage/AzureStorageBlob/Source/NetworkingPolicy.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient+Extensions.swift, sdk/storage/AzureStorageBlob/Source/TransferManager.swift, sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager+TransferDelegate.swift, sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
=> Network policy configurability

sdk/core/AzureCore/Source/DataStructures/Collections.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift
Closes #326.
Example usage:
```Swift
DispatchQueue.global(qos: .background).async {
for item in paged.syncIterator {
print(item.name)
}
}
```
```Swift
paged.forEachPage { page in
self.tableView.reloadData()
return false
}
```
=> Refactor PagedCollection to comport with guidelines

examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift
Fixes the issue of the demo app constantly complaining about the exhausted paged collection.
=> Fix paged collection issue.

sdk/core/AzureCore/Source/Pipeline/Policies/AuthenticationPolicy.swift, sdk/core/AzureCore/Source/Util/ConvertingInitializers.swift, sdk/storage/AzureStorageBlob/Source/Credentials/StorageCredentials.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift
Completes the engineering work for #160
We still need to add a sample azure function to show how to vend SAS tokens.
=> Allow SAS token to be refreshed

examples/AzureSDKDemoSwift/Source/Common.swift, sdk/core/AzureCore/Source/Pipeline/PipelineClient.swift, sdk/core/AzureCore/Source/Pipeline/Policies/UserAgentPolicy.swift, sdk/core/AzureCore/Tests/UserAgentPolicyTests.swift, sdk/storage/AzureStorageBlob/Source/Options/ClientOptions.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient+Extensions.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift, sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
Allows the user to set the applicationId and telemetryDisabled properties.
Partially completes #150.
=> Add TelemetryOptions

eng/pipelines/ci.yml
This PR adjusts the headers in a lot of files, we are getting rid of the misleading comment and instead adding a link to a (yet to be created aka.ms link).
=> Adjust CI YAML headers

eng/pipelines/templates/stages/archetype-sdk-client.yml
Remove azure-sdk-tools repository resource as its no longer needed.
=> Remove unneeded resource

Package.swift
=> Remove AzureStorageBlob from Package.swift

CONTRIBUTING.md
=> Fixing link to contribution guide

.jazzy/AzureCommunication.yml, sdk/communication/AzureCommunication/Source/Authentication/AutoRefreshUserCredential.swift, sdk/communication/AzureCommunication/Source/Authentication/CommunicationAuthenticationPolicy.swift, sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenCredential.swift, sdk/communication/AzureCommunication/Source/Authentication/CommunicationUserCredential.swift, sdk/communication/AzureCommunication/Source/Authentication/JwtTokenParser.swift, sdk/communication/AzureCommunication/Source/Authentication/StaticUserCredential.swift, sdk/communication/AzureCommunication/Source/Identifiers.swift
Fleshing out the comment blocks so Jazzy can populate the documentation
=> Documentation: Drafting documentation for the Authentication code

.jazzy/AzureCommunicationChat.yml, Package.swift
Add new target to Package.swift after feature/communication branch is merged to master.
=> Add new target to Package.swift

sdk/communication/AzureCommunication/Source/Authentication/CommunicationUserCredential.swift, sdk/communication/AzureCommunication/Source/Authentication/StaticUserCredential.swift
Removing the reference of JWT so they don't make assumption on type
=> [Documentation] Remove reference to jwt

.github/CODEOWNERS
This PR label adds rules to the CODEOWNERS file that were missing.
=> Add more PR labels.

AzureCommunication.podspec, AzureCommunicationCalling.podspec, AzureCommunicationChat.podspec, AzureCore.podspec, CHANGELOG.md, README.md, eng/ignore-links.txt, sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj, sdk/communication/AzureCommunication/README.md, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationChat/README.md, sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj, sdk/core/AzureCore/README.md, sdk/identity/AzureIdentity/AzureIdentity.xcodeproj/project.pbxproj, sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj
Prepared all of the packages to be released as beta.5
@raosanat Please add changelog entries to the appropriate section headers in CHANGELOG.md, and set the release date.
=> Prepare SDK for beta.5 release

Package.swift, eng/pipelines/templates/jobs/archetype-sdk-client.yml
Exclude the obj-c in package, and include swift build command into the CI
=> [Communication] - [Package] - Exclude ObjC files 

sdk/communication/AzureCommunicationChat/Source/Generated/Chat.swift, sdk/communication/AzureCommunicationChat/Source/Generated/ChatThreadOperation.swift, sdk/communication/AzureCommunicationChat/Source/Generated/Options/Chat+ListChatThreadsOptions.swift, sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+ListChatMessagesOptions.swift, sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+ListChatParticipantsOptions.swift, sdk/communication/AzureCommunicationChat/Source/Generated/Options/ChatThreadOperation+ListChatReadReceiptsOptions.swift, sdk/communication/AzureCommunicationChat/Source/Swagger/swagger.json
- $maxpagesize renaming was changed back to maxPageSize
- Changes to addParticipants path and status codes
- Tested locally on demo app
=> Updated chat participants + maxPageSize naming

AzureSDK.xcworkspace/contents.xcworkspacedata, examples/SignalingTestApp/SignalingTestApp.xcodeproj/project.pbxproj, examples/SignalingTestApp/SignalingTestApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata, examples/SignalingTestApp/SignalingTestApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, examples/SignalingTestApp/SignalingTestApp/AppDelegate.swift, examples/SignalingTestApp/SignalingTestApp/Assets.xcassets/AccentColor.colorset/Contents.json, examples/SignalingTestApp/SignalingTestApp/Assets.xcassets/AppIcon.appiconset/Contents.json, examples/SignalingTestApp/SignalingTestApp/Assets.xcassets/Contents.json, examples/SignalingTestApp/SignalingTestApp/Base.lproj/LaunchScreen.storyboard, examples/SignalingTestApp/SignalingTestApp/Base.lproj/Main.storyboard, examples/SignalingTestApp/SignalingTestApp/Info.plist, examples/SignalingTestApp/SignalingTestApp/SceneDelegate.swift, examples/SignalingTestApp/SignalingTestApp/ViewController.swift
=> add signaling test app

sdk/storage/AzureStorageBlob/Source/StorageStreamUploader.swift
This is a fix for the StorageStreamUploader class, previously the commitHeadersForRequest function omitted contentLength, which is then assumed to be 0 but is in actual fact a small xml string set in the commit function.
I have added an extra parameter to the commitHeadersForRequest function which then allows the commit function to work correctly.
I have also moved the init of the headers to after the assigment of the xmlData object
I was asked to mention @bsiegel as the reviewer.
=> StorageStreamUploader fix for SharedKeyCredentials (issue  #585)

sdk/communication/AzureCommunicationChat/Tests/ChatClientTests.swift, sdk/communication/AzureCommunicationChat/Tests/ChatClientUnitTests.swift, sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientTests.swift, sdk/communication/AzureCommunicationChat/Tests/ChatThreadClientUnitTests.swift, sdk/communication/AzureCommunicationChat/Tests/Util/TestUtil.swift
- Added a live test for sending HTML messages
- Cleaned up the test setup
=> Add test for HTML messages

sdk/communication/AzureCommunicationChat/Source/ChatClient.swift, sdk/communication/AzureCommunicationChat/Tests/ChatClientTests.swift, sdk/communication/AzureCommunicationChat/Tests/Util/RecordingUtil.swift
- SDK should set the repeatability-Request-ID if its not provided
=> Chat sets repeatability-Request-ID if its not provided

AzureSDK.xcworkspace/contents.xcworkspacedata, eng/pipelines/templates/jobs/archetype-sdk-client.yml
=> Disable smoke test from CI

AzureCommunication.podspec.json, AzureCommunicationChat.podspec.json, eng/pipelines/templates/jobs/archetype-sdk-client.yml
Fixes https://github.com/Azure/azure-sdk-for-ios/issues/698
=> [CI] - Task - Adding pod spec lint to pipeline as task

eng/pipelines/templates/jobs/archetype-sdk-client.yml
Add call to `eng-common-workflow-enforcer.yml`. Makes sure all eng/common changes follow the [eng/common workflow](https://github.com/Azure/azure-sdk-tools/blob/master/doc/common/common_engsys.md#workflow)
=> Add eng/common workflow enforcer

CHANGELOG.md
=> Update CHANGELOG.md for beta.10

CHANGELOG.md, sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj, sdk/communication/AzureCommunication/README.md, sdk/communication/AzureCommunication/Source/Authentication/AutoRefreshTokenCredential.swift, sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenCredential.swift, sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenRefreshOptions.swift, sdk/communication/AzureCommunication/Source/Authentication/ThreadSafeRefreshableAccessTokenCache.swift, sdk/communication/AzureCommunication/Tests/CommunicationPolicyTokenCredentialTests.swift, sdk/communication/AzureCommunication/Tests/CommunicationTokenCredentialTests.swift, sdk/communication/AzureCommunication/Tests/ObjCCommunicationTokenCredentialAsyncTests.m, sdk/communication/AzureCommunication/Tests/ObjCCommunicationTokenCredentialTests.m, sdk/communication/AzureCommunication/Tests/ObjCTokenParserTests.m, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationChat/Source/ChatClient.swift, sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift, sdk/communication/AzureCommunicationChat/Source/Token/PolicyTokenCredential.swift, sdk/communication/AzureCommunicationChat/Tests/PolicyTokenCredentialTests.swift
LInk to arch review feedback: https://github.com/Azure/azure-sdk-for-ios/pull/772
=> [Communication] - ArchBoard - Resolving issues brought up from arch review

sdk/communication/AzureCommunicationChat/README.md
Add section for how to receive message events using notifications.
=> Update chat README

AzureCommunicationCalling.podspec.json, eng/pipelines/templates/jobs/archetype-sdk-client.yml
Out-of-band release for AzureCommunicationCalling.
=> Release AzureCommunicationCalling 1.0.0-beta.12

eng/ignore-links.txt, examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift, examples/AzureSDKSmokeTest/Podfile, jazzy/AzureCore.yml, sdk/core/AzureCore/AzureCore.podspec.json, sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj, sdk/core/AzureCore/CHANGELOG.md
This will be the first AzureCore service tag in the mono repo and first tag in the SwiftPM-AzureCore repo.
=> Release AzureCore 1.0.0 beta.12

eng/pipelines/templates/stages/archetype-sdk-client.yml, sdk/communication/ci.yml, sdk/core/ci.yml, sdk/identity/ci.yml, sdk/storage/ci.yml
This PR puts the ```sdk/[service]/ci.yml``` files back in. At this point there are minimal changes to the stage template. After these files are added we can generate the pipelines using our automated pipeline generator and then start iterating on the release pipeline improvements (we need these files in place first to generate the pipelines).
=> Breakout pipelines.

sdk/template/ci.yml
Just adding the ```ci.yml``` file so that I can generate the template pipeline,
=> Add template ci.yml.

sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json, sdk/communication/AzureCommunicationChat/Package.swift
Updates Chat dependencies to latest version of AzureCore (beta.12) and AzureCommunicationCommon (>= 1.0.0).
=> Chat - Update dependencies

AzureSDK.xcworkspace/xcshareddata/xcschemes/all.xcscheme, AzureSDK.xcworkspace/xcshareddata/xcschemes/communication.xcscheme, AzureSDK.xcworkspace/xcshareddata/xcschemes/sdk.xcscheme, sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj, sdk/template/AzureTemplate/AzureTemplate.xcodeproj/xcshareddata/xcschemes/AzureTemplate.xcscheme
Update to ensure that the various schemes run all of the correct tests.
=> Update test schemes

AzureSDK.xcworkspace/contents.xcworkspacedata, Podfile, sdk/communication/AzureCommunicationChat/Tests/ChatClientDVRTests.swift, sdk/test/AzureTest/DVRSessionTransport.swift
Makes the DVRSessionTransport honor the TEST_MODE environment variable.
=> AzureTest playback mode based on TEST_MODE

sdk/communication/AzureCommunicationChat/Tests/ChatClientDVRTests.swift
=> Recordings on a per-test basis

sdk/communication/ci.yml, sdk/core/ci.yml, sdk/identity/ci.yml, sdk/storage/ci.yml, sdk/template/ci.yml
This PR adds ```main``` to the CI and PR triggers.
=> Add main to CI files.

.github/CODEOWNERS
=> Remove self from codeowners.

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
ACS Calling release for 1.1.0 Stable build
=> ACS Calling Release 1.1.0

jazzy/AzureCommunicationChat.yml, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationChat/CHANGELOG.md, sdk/communication/AzureCommunicationChat/README.md
Points podspec to Chat homepage instead of main repo homepage.
=> AzureCommunicationChat 1.0.1

sdk/communication/AzureCommunicationChat/Source/ChatThreadClient.swift, sdk/communication/AzureCommunicationChat/Source/Signaling/Events/ChatEvent.swift, sdk/communication/AzureCommunicationChat/Tests/ChatClientUnitTests.swift
=> Fix up Chat Tests

sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/xcshareddata/xcschemes/AzureCommunicationChat.xcscheme, sdk/test/AzureTest/Source/DVRSessionTransport.swift
Parameterizes the recording destination folder instead of hard-coding Chat.
=> Remove recording destination hard coding

sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json, sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCommon/CHANGELOG.md, sdk/communication/AzureCommunicationCommon/Package.swift
Remove AzureCore dependency in Package.swift to match podspec.
=> Fix Package.swift for AzureCommunicationCommon

sdk/core/AzureCore/Source/Util/RequestString.swift
Necessary change to support Autorest.swift.
https://github.com/Azure/autorest.swift/pull/318
=> Improve JSON serialization of optional types.

eng/scripts/Language-Settings.ps1, eng/scripts/Update-PkgVersion.ps1
Logic that enable updating of package version in the repo.
=> Add script for bumping up the package version

eng/scripts/Language-Settings.ps1
- Change LanguageDisplayName from `Swift` to `iOS`.
=> Update Language Dispaly Name

jazzy/AzureCommunicationChat.yml, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationChat/CHANGELOG.md, sdk/communication/AzureCommunicationChat/README.md
=> AzureCommunicationChat 1.1.0-beta.1

jazzy/AzureCommunicationChat.yml, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationChat/CHANGELOG.md, sdk/communication/AzureCommunicationChat/README.md
- Bump version
- Update CHANGELOG
=> AzureCommunicationChat 1.1.0-beta.2

sdk/communication/AzureCommunicationCommon/Source/Authentication/CommunicationTokenCredential.swift
Fixing documentation warning
Resolving git issue: https://github.com/Azure/azure-sdk-for-ios/issues/1038
=> [CommunicationTokenCredential] Fixing documentation warning

eng/scripts/version.py
=> Fix Version update script

eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/pipelines/templates/variables/globals.yml
Related to Azure/azure-sdk-tools#2273
=> Generate manifest alongside build artifacts

AzureSDK.xcworkspace/xcshareddata/xcschemes/sdk.xcscheme, eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/pipelines/templates/stages/archetype-ios-release.yml, eng/pipelines/templates/variables/globals.yml, sdk/communication/AzureCommunicationChat/Tests/TrouterEventUtilTests.swift
Mac 11 agent capacity has finally been added to the hosted pool: https://github.com/actions/virtual-environments/issues/4060
Fixes #974
=> Use macOS-11 as default pipeline image

sdk/core/AzureCore/CHANGELOG.md, sdk/core/AzureCore/Source/Pipeline/Policies/ContentDecodePolicy.swift, sdk/core/AzureCore/Source/Pipeline/Transport/URLSessionTransport.swift
=> Fix broken onError chain in AzureCore

examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift, examples/AzureSDKSmokeTest/Podfile, jazzy/AzureCore.yml, sdk/core/AzureCore/AzureCore.podspec.json, sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj, sdk/core/AzureCore/README.md
=> Prepare AzureCore 1.0.0-beta.14

sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationChat/Tests/Recordings/test_CreateThread_WithoutParticipants.json, sdk/communication/AzureCommunicationChat/Tests/Recordings/test_ListThreads_ReturnsChatThreadItems.json, sdk/test/AzureTest/Source/Filters/LargeBodyFilter.swift
The LargeBodyFilter value was set too low. This will unblock the Chat team until a more robust setting can be used.
=> Fix large body issues.

sdk/communication/AzureCommunicationChat/Tests/Recordings/test_CreateThread_WithoutParticipants.json, sdk/communication/AzureCommunicationChat/Tests/Recordings/test_ListThreads_ReturnsChatThreadItems.json, sdk/communication/AzureCommunicationChat/Tests/TestSettings.swift, sdk/communication/AzureCommunicationChat/Tests/TrouterSettingsUnitTest.swift
=> Fix the DVR live tests recordings

examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift, examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift, examples/AzureStorageBlobDemo/Source/Common.swift, examples/AzureStorageBlobDemo/Source/MainViewController.swift, sdk/communication/AzureCommunicationCommon/Source/Authentication/JwtTokenParser.swift, sdk/core/AzureCore/Source/DataStructures/XMLMap.swift, sdk/core/AzureCore/Source/Pipeline/PipelineContext.swift, sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift, sdk/core/AzureCore/Source/Pipeline/Policies/UserAgentPolicy.swift, sdk/core/AzureCore/Source/Pipeline/Transport/DataStringConvertible.swift, sdk/core/AzureCore/Source/Pipeline/Transport/URLSessionTransport.swift, sdk/core/AzureCore/Source/Util/ReachabilityManager.swift, sdk/core/AzureCore/Tests/RequestParametersTests.swift, sdk/storage/AzureStorageBlob/Source/Credentials/StorageSASCredential.swift, sdk/storage/AzureStorageBlob/Source/Credentials/StorageSASToken.swift, sdk/storage/AzureStorageBlob/Source/Credentials/StorageSharedKeyCredential.swift, sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataClass.swift, sdk/storage/AzureStorageBlob/Source/DataStructures/TransferCollection.swift, sdk/storage/AzureStorageBlob/Source/Models/ContainerProperties.swift, sdk/storage/AzureStorageBlob/Source/Operations/BlobDownloadOperations.swift, sdk/storage/AzureStorageBlob/Source/Operations/BlobUploadOperations.swift, sdk/storage/AzureStorageBlob/Source/Operations/BlobsOperations.swift, sdk/storage/AzureStorageBlob/Source/Operations/ContainersOperations.swift, sdk/storage/AzureStorageBlob/Source/Options/ClientMethodOptions.swift, sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift, sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift, sdk/storage/AzureStorageBlob/Source/StorageStreamUploader.swift, sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
Upgrades to latest of these tools. Wiki updated to specify exact versions for consistent in PRs.
=> Updates for SwiftLint and SwiftFormat

jazzy/AzureCommunicationChat.yml, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationChat/Package.swift, sdk/communication/AzureCommunicationChat/README.md
Reverts Azure/azure-sdk-for-ios#1205
=> Revert "Bump up the chat version"

sdk/communication/AzureCommunicationChat/README.md, sdk/communication/AzureCommunicationChat/Source/Generated/Options/ListChatMessagesOptions.swift
=> Improving documents

jazzy/AzureCommunicationUICalling.yml
A new yml file used to generate Jazzy doc in github.io
=> Add jazzy file for AzureCommunicationUICalling

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
Here's the ApiView diff of 2.2.0:
https://apiview.dev/Assemblies/Review/14e758f61b3b4a8088612a9d424a1cdd?diffRevisionId=d0be5c7e31224921b90e9fa9f590e43d&doc=False&diffOnly=False&revisionId=99f3ecb173214708845269d668b3414f
=> AzureCommunicationCalling 2.2.0

eng/pipelines/templates/jobs/archetype-sdk-client.yml
This will unblock PRs in case of hanging CG step.
CC: @scbedd
=> CG only runs on internal

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/14e758f61b3b4a8088612a9d424a1cdd/481bb073dedb41dd88e6fcea8f327e1b?diffRevisionId=99f3ecb173214708845269d668b3414f&doc=False&diffOnly=True
=> AzureCommunicationCalling-2.3.0-beta.1

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/14e758f61b3b4a8088612a9d424a1cdd
=> AzureCommunicationCaling-2.3.0-beta.2

eng/scripts/Publish-SwiftMirrorRedirectReadme.ps1, eng/scripts/Publish-SwiftPackage.ps1, sdk/template/AzureTemplate/AzureTemplate.podspec.json, sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj, sdk/template/AzureTemplate/CHANGELOG.md, sdk/template/AzureTemplate/Package.swift, sdk/template/AzureTemplate/README.md
Explicitly pass the azure-sdk bot account
as the user for the commits we are pushing
to the SwiftPM repos.
Update the template version in order to test
the publishing changes.
=> Fix SwiftPM publishing scripts

examples/AzureSDKSmokeTest/AzureSDKSmokeTest.xcodeproj/project.pbxproj
There's no reason for the smoke test to format and lint sources.
=> Fix CI Part 2 

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/14e758f61b3b4a8088612a9d424a1cdd?revisionId=e072c9b27d604fc2ad3b851be10992a0&doc=False
=> AzureCommunicationCalling_2.2.2

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/14e758f61b3b4a8088612a9d424a1cdd/b236ec4d8bac483da9ed5691a36c1e9a?diffRevisionId=3ec5ce8c194c4bb8a0ddf6f5f6d1bae2&doc=False&diffOnly=True
=> AzureCommunicationCalling_2.3.0-beta.3

jazzy/AzureCommunicationUICalling.yml, jazzy/AzureCommunicationUIChat.yml
As we are close to official release of ACS UI Chat, I am adding Jazzy config for it so API reference doc would be available after release
=> Added Jazzy Config for ACS UI Chat

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/14e758f61b3b4a8088612a9d424a1cdd?diffRevisionId=b236ec4d8bac483da9ed5691a36c1e9a&diffOnly=False&revisionId=cc58daab780142f791c8b4c95676d35f&doc=False
=> AzureCommunicationCalling 2.3.0-beta.4

jazzy/AzureCommunicationUIChat.yml
Release date hasn't been set yet, please don't publish it yet. thanks!
=> Updated Chat Version

jazzy/AzureCommunicationUICalling.yml
=> [Documentation] Update jazzy module version 

examples/AzureSDKSmokeTest/AzureSDKSmokeTest.xcodeproj/project.pbxproj, examples/AzureSDKSmokeTest/AzureSDKSmokeTest.xcworkspace/contents.xcworkspacedata, examples/AzureSDKSmokeTest/AzureSDKSmokeTest.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, jazzy/AzureCommunicationChat.yml, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationChat/CHANGELOG.md, sdk/communication/AzureCommunicationChat/README.md
Updated CHANGELOG
Updated required versions and tag
Updated SmokeTest project
=> AzureCommunicationChat 1.3.1

.github/CODEOWNERS
Updating CODEOWNERS for communication identity and common: [User Story 3194324](https://skype.visualstudio.com/SPOOL/_workitems/edit/3194324): [All SDK Platform] Remove Petr& Olena from the CODEOWNERs list
=> [Communication Identity] Update codeowners

jazzy/AzureCommunicationUICalling.yml
Updating jazzy Azure Communication UI Calling version 1.3.0
=> Updating jazzy Azure Communication UI Calling version 1.3.0

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/209f39ac4ecf434ea5d2257fa0774f2d?diffRevisionId=af4858864f864ab5ac7bd8a4aab7800a&diffOnly=False&revisionId=05c9aaeabb164bc4bc64ecc91b075b2e&doc=False
=> Release iOS SDK AzureCommunicationCalling-2.3.0-beta.5

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/209f39ac4ecf434ea5d2257fa0774f2d?diffRevisionId=884eebb79529451e8daddad35dcdbf20&diffOnly=True&revisionId=becf31ba4f4b4c3b96e924d5df967da0&doc=False
Adding dominant speaker feature
=> Azure communication calling 2.3.0

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/209f39ac4ecf434ea5d2257fa0774f2d?revisionId=41f3878efbd24c1f881e808d7935a2f4&doc=False
=> AzureCommunicationCalling-2.4.0

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/994dc64224614433a2685a0a75e184c0
=> Azure Communication Calling 2.5.0

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/994dc64224614433a2685a0a75e184c0
=> AzureCommunicationCalling 2.6.0

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/994dc64224614433a2685a0a75e184c0
=> Azure Communication Calling iOS SDK 2.7.0-beta.1

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/994dc64224614433a2685a0a75e184c0
=> AzureCommunicationCalling 2.7.0-beta.2

eng/common/scripts/TypeSpec-Project-Generate.ps1, eng/common/scripts/common.ps1
Reverts Azure/azure-sdk-for-ios#1596
=> Revert "Sync eng/common directory with azure-sdk-tools for PR 6823"

sdk/core/AzureCore/Source/DataStructures/AzureDate.swift
Fix the CI to workaround a SwiftFormat regression and unblock the build.
=> Workaround SwiftFormat bug

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/994dc64224614433a2685a0a75e184c0?diffRevisionId=da4d4793554b4b729f4d17dfbecadb64&diffOnly=False&revisionId=62c01233048d4ffa8d0328bdf6518a20&doc=False
=> Azure Communication Calling 2.6.1

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/994dc64224614433a2685a0a75e184c0?diffRevisionId=0946de9fae9b41ab82916cc32d0dd8b5&diffOnly=False&revisionId=997a2a4acc874c5aa1f1643d44ddffe5&doc=False
=> AzureCommunicationCalling 2.7.0-beta.3

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/994dc64224614433a2685a0a75e184c0?revisionId=1130980cdd304ea28b3e2387e18feb95&doc=False
=> AzureCommunicationCalling iOS 2.7.0

sdk/communication/AzureCommunicationCommon/CHANGELOG.md, sdk/communication/AzureCommunicationCommon/Source/Identifiers.swift, sdk/communication/AzureCommunicationCommon/Tests/CommunicationIdentifierTest.swift, sdk/communication/AzureCommunicationCommon/Tests/CreateCommunicationIdentifier.swift
Added MicrosoftTeamsAppIdentifier.
=> Add MicrosoftTeamsAppIdentifier

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d/87271311eba647259e99463e0f092181?diffRevisionId=61408c06162848e197cb8504183fdb14&doc=False&diffOnly=True
=> AzureCommunicationCalling 2.8.0-beta.2

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d/2a6ecb5e4bf14a6c9f62e575d5856112?diffRevisionId=87271311eba647259e99463e0f092181&doc=False&diffOnly=True
=> AzureCommunicationCalling_2.8.0-beta.3

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d/8950b0edb507498c97f9796323f2e934?diffRevisionId=1130980cdd304ea28b3e2387e18feb95&doc=False&diffOnly=True
=> AzureCommunicationCalling 2.8.0

jazzy/AzureCommunicationChat.yml, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationChat/CHANGELOG.md, sdk/communication/AzureCommunicationChat/README.md
Update AzureCommunicationChat from 1.3.3 to 1.3.4
=> Update AzureCommunicationChat to 1.3.4

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d/297ff48efc2f4af6b8ff2e06724d79d7?diffRevisionId=8950b0edb507498c97f9796323f2e934&doc=False&diffOnly=True
=> Azure Communication Calling 2.9.0

eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/pipelines/templates/jobs/live.tests.yml, eng/pipelines/templates/stages/archetype-ios-release.yml, eng/pipelines/templates/stages/archetype-sdk-client.yml, eng/pipelines/templates/stages/archetype-sdk-tests.yml, eng/pipelines/templates/variables/image.yml, sdk/template/AzureTemplate/AzureTemplate.podspec.json, sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj, sdk/template/AzureTemplate/CHANGELOG.md, sdk/template/AzureTemplate/README.md
[Successful Template Release](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3620385&view=logs&j=b0bfa1f3-db9a-5134-fed5-79a504466d6e)
Merging after successful template release.
=> `1ES-Template` Conversion

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d/3db5ba2baadd4de9962a907b49b76d56?diffRevisionId=297ff48efc2f4af6b8ff2e06724d79d7&doc=False&diffOnly=True
=> Azure Communication Calling 2.10.0

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d/c320ec6df0394f7d88889f98a7c5d318?diffRevisionId=3db5ba2baadd4de9962a907b49b76d56&doc=False&diffOnly=True
=> Azure Communication Calling 2.10.1

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d?revisionId=33578f860b9840b697391209614d8c8b&diffOnly=True&doc=False&diffRevisionId=c320ec6df0394f7d88889f98a7c5d318
=> Azure Communication Calling 2.11.0

jazzy/AzureCommunicationChat.yml, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationChat/README.md
Release AzureCommunicationChat 1.3.5
=> Release AzureCommunicationChat 1.3.5

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d/699e2a743d4e49afb79d0bad99d57774?diffRevisionId=0e738e4842674e788a4a8d439cf502d2&doc=False&diffOnly=True
=> Azure Communication Calling 2.12.0-beta.1

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d/ea7171e3708a4938bf4725a8567a0d28?diffRevisionId=699e2a743d4e49afb79d0bad99d57774&doc=False&diffOnly=True
=> Azure Communication Calling 2.12.0-beta.2

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
[2.13.0-beta.1 ApiView Diff](https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d/942552e806804267a4b66ef593eb7aa5?diffRevisionId=ea7171e3708a4938bf4725a8567a0d28&doc=False&diffOnly=True)
=> Azure Communication Calling 2.13.0-beta.1

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
<< INSERT iOS APIVIEW REVISION DIFF HERE >>
=> Azure Communication Calling 2.13.0-beta.2

.github/CODEOWNERS
=> Update 1espt codeowners

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
<< INSERT iOS APIVIEW REVISION DIFF HERE >>
=> Azure Communication Calling 2.14.0-beta.1

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d/d60f86893c1e46aca45550d0b7fbfe8d?diffRevisionId=304bf3f9e7614fcf94578742520e09fc&doc=False&diffOnly=True
=> Azure Communication Calling 2.13.1

jazzy/AzureCommunicationChat.yml, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json, sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationChat/CHANGELOG.md, sdk/communication/AzureCommunicationChat/README.md
Release AzureCommunicationChat 1.3.6
=> Release AzureCommunicationChat 1.3.6

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d?revisionId=8abf77c1a1d741bf83aa22e1f304f031&diffOnly=False&doc=False&diffRevisionId=112a803e9c454bcba0b9c5740e311dcf
=> Azure Communication Calling 2.14.0-beta.2

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d/6eaf2e0a19334c89b305fc53b9eee2cf?diffRevisionId=8abf77c1a1d741bf83aa22e1f304f031&doc=False&diffOnly=True
=> Azure Communication Calling 2.14.0-beta.3

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d?revisionId=d2d1f1a88e2e4343a6133e0fae773787&diffOnly=True&doc=False&diffRevisionId=d60f86893c1e46aca45550d0b7fbfe8d
=> Azure Communication Calling 2.14.0

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d/9ffece0fdfb94a86b9b92283c5cd2d4d?diffRevisionId=d2d1f1a88e2e4343a6133e0fae773787&doc=False&diffOnly=True
=> Azure Communication Calling 2.14.1

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://apiview.dev/Assemblies/Review/80768c5191c748a69f83e4e2d42bd97d?revisionId=13b97aa398bb46d989abe8780b4097b7&diffOnly=True&doc=False&diffRevisionId=6eaf2e0a19334c89b305fc53b9eee2cf
=> Azure Communication Calling 2.15.0-beta.1

AzureSDK.xcworkspace/contents.xcworkspacedata, jazzy/AzureAIVisionCore.yml, jazzy/AzureAIVisionFaceUI.yml
* Updates documentation
```
[ ] Yes
[x] No
```
What kind of change does this Pull Request introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```
*  Read the code
Verify that the following are true:
* `AzureAIVisionCore` and `AzureAIVisionFace` does not exist on homepage
* `AzureAIVisionFaceUI/Enums/LivenessStatus.html` does not exist
* `AzureAIVisionFaceUI/Enums/RecognitionStatus.html` does not exist
* `AzureAIVisionFaceUI/Enums/LivenessError.html#/c:@E@AZFaceLivenessFailureReason@AZFaceLivenessFailureReasonClientVersionNotSupported` exists
=> updates AI Vision docs to 1.0.0

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
https://spa.apiview.dev/review/80768c5191c748a69f83e4e2d42bd97d?activeApiRevisionId=ef556727a38346aa8d50cf8a7c7c22de&diffApiRevisionId=48e528f63a3647c88032e6a637932994&diffStyle=nodes
=> Azure Communication Calling 2.15.0

eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/pipelines/templates/variables/globals.yml, eng/pipelines/templates/variables/image.yml
=> Bump Pinned Platform Version

jazzy/AzureAIVisionFaceUI.yml
* Updates documentation
```
[ ] Yes
[x] No
```
What kind of change does this Pull Request introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```
*  Read the code
Verify that the following are true:
* `AzureAIVisionFaceUI/index.html` now shows the version 1.1.0
=> updates AI Vision docs to 1.1.0

eng/pipelines/templates/jobs/archetype-sdk-client.yml, eng/pipelines/templates/stages/archetype-ios-release.yml, eng/pipelines/templates/stages/archetype-sdk-client.yml, sdk/template/AzureTemplate/AzureTemplate.podspec.json, sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj, sdk/template/AzureTemplate/CHANGELOG.md, sdk/template/AzureTemplate/README.md
Resolves #2008 
Hilariously enough @weshaggard the first attempt to release _100%_ hit that SAML error you were mentioning on your way out today. I'm retrying it now!
[Example successful release](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4646258&view=results)
=> Resolve 1ES Release warning

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://spa.apiview.dev/review/80768c5191c748a69f83e4e2d42bd97d?activeApiRevisionId=ef556727a38346aa8d50cf8a7c7c22de&diffApiRevisionId=baa4fe4f3894495c853e1e5fd519cea8
- Bug fix for PSTN mute/unmute
=> Azure Communication Calling 2.15.1

examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift, examples/AzureSDKSmokeTest/Podfile, jazzy/AzureCore.yml, sdk/core/AzureCore/AzureCore.podspec.json, sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj, sdk/core/AzureCore/CHANGELOG.md, sdk/core/AzureCore/README.md, sdk/core/AzureCore/Source/DataStructures/AzureDate.swift, sdk/core/AzureCore/Source/DataStructures/CancellationToken.swift, sdk/core/AzureCore/Source/DataStructures/Collections.swift, sdk/core/AzureCore/Source/DataStructures/XMLMap.swift, sdk/core/AzureCore/Source/DataStructures/XMLTree.swift, sdk/core/AzureCore/Source/Pipeline/Pipeline.swift, sdk/core/AzureCore/Source/Pipeline/PipelineClient.swift, sdk/core/AzureCore/Source/Pipeline/PipelineContext.swift, sdk/core/AzureCore/Source/Pipeline/Policies/ContentDecodePolicy.swift, sdk/core/AzureCore/Source/Pipeline/Policies/LoggingPolicy.swift, sdk/core/AzureCore/Source/Pipeline/Policies/UserAgentPolicy.swift, sdk/core/AzureCore/Source/Pipeline/Transport/RequestParameters.swift, sdk/core/AzureCore/Source/Providers/BundleInfoProvider.swift, sdk/core/AzureCore/Source/Providers/LocaleInfoProvider.swift, sdk/core/AzureCore/Source/Providers/PlatformInfoProvider.swift, sdk/core/AzureCore/Source/Util/ApplicationUtil.swift, sdk/core/AzureCore/Source/Util/KeychainUtil.swift, sdk/core/AzureCore/Source/Util/ReachabilityManager.swift, sdk/core/AzureCore/Tests/CollectionsTests.swift, sdk/core/AzureCore/Tests/Stubs/TestClient.swift, sdk/core/AzureCore/Tests/XMLModelTests.swift
=> AzureCore 1.0.0-beta.16

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCalling/CHANGELOG.md
https://spa.apiview.dev/review/80768c5191c748a69f83e4e2d42bd97d?activeApiRevisionId=70c66ad000324e03bc45e1b6a628b9f0
=> Azure Communication Calling 2.16.0-beta.1

sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj, sdk/communication/AzureCommunicationCommon/CHANGELOG.md, sdk/communication/AzureCommunicationCommon/Source/Identifiers.swift, sdk/communication/AzureCommunicationCommon/Tests/CommunicationIdentifierTest.swift, sdk/communication/AzureCommunicationCommon/Tests/CreateCommunicationIdentifier.swift
This PR includes the following changes:
* Added Phone Number identifier extensions
* Added TeamsExtensionUserIdentifier
* Covered with tests createCommunicationIdentifier
Generated APIView -  [AzureCommunicationCommon - 1.3.0](https://spa.apiview.dev/review/b8fa2cabba944cd693d10032b218b143?activeApiRevisionId=8048bb704b0d4e85bfc31f81f25a3389&diffApiRevisionId=567522021c07492682ef666c62d6c666)
=> [ACS Common] Teams Phone Extensibility updates

sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json, sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.xcodeproj/project.pbxproj
[2.16.0-2.15.1](https://spa.apiview.dev/review/80768c5191c748a69f83e4e2d42bd97d?activeApiRevisionId=ba9d552867ac427792a9f906976fa965&diffApiRevisionId=d997c8eeea004e5a829d4ca1ab370fca&diffStyle=trees)
=> Azure Communication Calling 2.16.0
