Azure/azure-sdk-for-ios

- AzureCore/Source/DateFormat.swift
- AzureData/AzureData.xcodeproj/project.pbxproj
- AzureData/Source/Resources/ResponseMetadata.swift
- AzureData/Source/Response.swift
- AzureData/Tests/ResponseMetadataTests.swift
Fixes #15.
- Add Azure CosmosDB related metadata in the `Response` Object.
> Add metadata to the Response object

- AzureData/AzureData.xcodeproj/project.pbxproj
- AzureData/Source/AzureData.swift
- AzureData/Source/AzureDataExtensions.swift
- AzureData/Source/DocumentClient.swift
- AzureData/Source/Resources/Attachment.swift
- AzureData/Source/Resources/Document.swift
- AzureData/Source/Resources/DocumentCollection.swift
- AzureData/Source/Resources/StoredProcedure.swift
- AzureData/Source/Resources/Trigger.swift
- AzureData/Source/Resources/UserDefinedFunction.swift
- AzureData/Source/SupportsPermissionToken.swift
Fixes #63.
- Restrict Permission create/replace APIs to resources supporting permission token
> Restrict Permission create/replace APIs to resources supporting permission token

- AzureData/Source/AzureData.swift
- AzureData/Source/AzureDataExtensions.swift
- AzureData/Source/DocumentClient.swift
- AzureData/Tests/AzureDataTests.swift
- AzureData/Tests/StoredProcedureTests.swift
Fixes #62.
- Add `AzureData.execute` override that takes a `StoredProcedure` in parameter.
> Add StoredProcedure execute override that takes StoredProcedure object

- AzureCore/AzureCore.xcodeproj/project.pbxproj
- AzureCore/Source/ReachabilityManager.swift
- AzureCore/Source/ReachabilityManagerType.swift
- AzureCore/Tests/ReachabilityManagerTests.swift
- AzureData/AzureData.xcodeproj/project.pbxproj
- AzureData/Source/DocumentClient.swift
- AzureData/Source/ResourceCache.swift
- AzureData/Source/ResourceOracle.swift
- AzureData/Source/Response.swift
- AzureData/Tests/Extensions.swift
- AzureData/Tests/Info.plist
- AzureData/Tests/OfflineTests.swift
- AzureData/Tests/_AzureDataTests.swift
Fixes #69 and #71.
- Fix the issue preventing some cached resources from being loaded when the network is not reachable
- Delete a resource from the cache if the remote database returns `404`
- Refactor `ReachabilityManager` to make it testable
- Add tests for the offline capabilities
> Review offline caching and add tests

- AzureData/AzureData.xcodeproj/project.pbxproj
- AzureData/Source/DocumentClient.swift
- AzureData/Source/DocumentClientError.swift
- AzureData/Source/MSHttpHeader.swift
- AzureData/Source/ResourceCache.swift
- AzureData/Source/ResourceLocation.swift
- AzureData/Source/ResourceOracle.swift
- AzureData/Source/ResourceWriteOperation.swift
- AzureData/Source/ResourceWriteOperationQueue.swift
- AzureData/Source/Resources/ResourceSystemProperties.swift
- AzureData/Source/Resources/StoredProcedure.swift
- AzureData/Source/Response.swift
- AzureData/Source/UtilityExtensions.swift
- AzureData/Tests/Extensions.swift
- AzureData/Tests/MockReachabilityManager.swift
- AzureData/Tests/MockURLSession.swift
- AzureData/Tests/OfflineReadTests.swift
- AzureData/Tests/OfflineWriteTests.swift
- AzureData/Tests/_AzureDataTests.swift
Fixes #73.
- Queue write operations (create, replace and delete) while offline
- Perform write operations locally while offline
- Automatically push local changes to the remote database as soon as the network becomes reachable
- Notify observers when pending writes are performed online
- Add tests
> Offline Write

- Azure.xcworkspace/contents.xcworkspacedata
Hi,
I just checked out the project and found that the `.xcworkspace` contained an invalid  reference to the AzureData ObJC project file so I fixed it.
> Fix project reference in workspace

- AzureData/Source/Geometry/Query+Geometry.swift
- AzureData/Source/Query.swift
- AzureData/Source/ResourceCache.swift
- AzureData/Source/Resources/DocumentContainer.swift
- AzureData/Tests/PointTests.swift
- Make there `where` operator for geometric queries more explicit (e.g. `where(distanceFrom:to:is:)`)
- Add the `and` operator support to geometric queries
- Fix a bug where `altLink` and `etag` were assigned to themselves in `DocumentContainer`
- Store the links (self and alt) in the resource oracle for resources returned as a result of a query
> Geometry Query API Updates

- AzureData/AzureData.xcodeproj/project.pbxproj
- AzureData/Source/AzureData.swift
- AzureData/Source/AzureDataExtensions.swift
- AzureData/Source/DocumentClient.swift
- AzureData/Source/Resources/Document.swift
- AzureData/Tests/_AzureDataTests.swift
- AzureData/Tests/_StoredProcedureTests.swift
Fixes #121.
- Adds overloads of `execute(storedProcedure...)` with a new parameter for the partition key
- Updates the tests
> Add support for partition keys when executing stored procedures

- AzureAuth/AzureAuth.xcodeproj/project.pbxproj
- AzureCore/AzureCore.xcodeproj/project.pbxproj
- AzureCore/Source/DateFormat.swift
- AzureCore/Source/HttpHeader.swift
- AzureCore/Source/HttpMethod.swift
- AzureData/AzureData.xcodeproj/project.pbxproj
- AzureData/README.md
- AzureData/Source/AzureData.swift
- AzureData/Source/AzureDataExtensions.swift
- AzureData/Source/DocumentClient.swift
- AzureData/Source/DocumentClientError.swift
- AzureData/Source/MSHttpHeader.swift
- AzureData/Source/Query.swift
- AzureData/Source/ResourceWriteOperation.swift
- AzureData/Source/Resources/DocumentContainer.swift
- AzureData/Source/Resources/DocumentProperties.swift
- AzureData/Tests/DocumentTests.swift
- AzureMobile/AzureMobile.xcodeproj/project.pbxproj
- AzurePush/AzurePush.xcodeproj/project.pbxproj
- AzureStorage/AzureStorage.xcodeproj/project.pbxproj
Thanks for taking the time to contribute. Please take a moment to fill out the information below.
Fixes #122.
- Fix some warnings
- Improve the `DocumentMetadata` model by removing the `id` field (which belong in the `Document` protocol)
- Add support for querying a subset of documents properties (see the [updated documentation](https://github.com/Azure/Azure.iOS/compare/feature/partial-queries?expand=1#diff-7f894c0373c91b36a8a4e11680fafd14R475) for the usage of the new API functions).
- Update the documentation
> Add support for partial document querying

- AzureData/Source/DocumentClient.swift
Fixes #112 by adding partition key to call.
> fix issue #112 : AzureData.replace throwing partition key error

- AzureCore/Source/Response.swift
- AzureData/Source/DocumentClient.swift
- AzureData/Source/ResourceWriteOperationQueue.swift
- AzureData/Source/ResponseExtensions.swift
- AzurePush/Source/NotificationClient.swift
Fixes #127 
We created `AzureCore.Result` before a `Result` type was added to Swift.  Fortunately our type was similar enough to Swift's implementation that minimal changes were required to update to use `Swift.Result` and remove `AzureCore.Result` altogether.
> fix issue #127 : Replace AzureCore.Result with Swift.Result

- sdk/appconfiguration/ci.yml
- sdk/cognitiveservices/ci.yml
- sdk/core/ci.yml
- sdk/storage/ci.yml
- sdk/textanalytics/ci.yml
This PR disables CI builds on feature branches. One of the patterns that we've seen lately is small teams that work on a feature branch doing merges from master (instead of a rebase). Because we have multiple pipelines in the repo many of those pipelines will trigger because of the scope of the changes that have been merged in, causing a build storm.
By disabling CI builds on feature branches we can mitigate that, at the expense of CI feedback on the feature branch. Builds for PRs to that feature branch would still work however.
> Disable CI builds on feature branches.

- examples/AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/project.pbxproj
- sdk/core/AzureCore/Tests/CollectionsTests.swift
- sdk/core/AzureCore/Tests/HTTPRequestTests.swift
- sdk/core/AzureCore/Tests/PipelineRequestTests.swift
- sdk/core/AzureCore/Tests/PipelineTests.swift
- sdk/core/AzureCore/Tests/UtilTests.swift
- sdk/core/AzureCore/Tests/XMLModelTests.swift
Refactors test names to follow the `test_[thing]_[expectation]` pattern in #184
> Refactor test names

- examples/AzureSDKDemoSwift/AzureSDKDemoSwift.entitlements
- examples/AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/project.pbxproj
- examples/AzureSDKDemoSwift/Source/Common.swift
- examples/AzureSDKDemoSwift/Source/Supporting Files/Info.plist
The recent update to the app bundle identifiers broke the auth in the demo app. This fixes up the necessary references.
> Update app bundle identifier.

- sdk/appconfiguration/AzureAppConfiguration/AzureAppConfiguration.xcodeproj/project.pbxproj
- sdk/cognitiveservices/AzureCSComputerVision/AzureCSComputerVision.xcodeproj/project.pbxproj
- sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
- sdk/storage/AzureStorageBlob/AzureStorageBlob.xcodeproj/project.pbxproj
- sdk/textanalytics/AzureCSTextAnalytics/AzureCSTextAnalytics.xcodeproj/project.pbxproj
Relates to: #174 
This will produce a .swiftinterface file for each module. This file is used by Swift 5.1's module stability feature to enable binary modules to be used with all newer compilers.
Another benefit is that the .swiftinterface file is text-based and we can easily diff them to compare the differences in the public interface between builds. It even includes the list of imports in the project which we could analyze to alert when a new dependency is introduced.
> Enable module stability when building

- Scripts/swiftlint.sh
This fixes an issue where running the script from Xcode could result in the tools not being able to locate their config files correctly and would apply the default ruleset instead.
> Specify path of config files in swiftformat

- sdk/core/AzureCore/Tests/AddDatePolicyTests.swift
The AddDate test names were wrong (copy-paste error).
Also added a test to validate an assumption not previously covered.
> Fix AddDate test names

- examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift
- examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift
- examples/AzureSDKDemoSwift/Source/Common.swift
- sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataClass.swift
- sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataProperties.swift
- sdk/storage/AzureStorageBlob/Source/Data/BlockTransfer+CoreDataClass.swift
- sdk/storage/AzureStorageBlob/Source/Data/BlockTransfer+CoreDataProperties.swift
- sdk/storage/AzureStorageBlob/Source/Data/MultiBlobTransfer+CoreDataClass.swift
- sdk/storage/AzureStorageBlob/Source/Data/MultiBlobTransfer+CoreDataProperties.swift
- sdk/storage/AzureStorageBlob/Source/Data/Transfer.swift
- sdk/storage/AzureStorageBlob/Source/Operation/BlobDownloadOperations.swift
- sdk/storage/AzureStorageBlob/Source/Operation/BlockOperations.swift
- sdk/storage/AzureStorageBlob/Source/Operation/ResumableOperation.swift
- sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift
- sdk/storage/AzureStorageBlob/Source/TransferManager.swift
- sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager+ResumableOperationQueueDelegate.swift
- sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
This way, a customer only has to provide the restoration ID when
initializing a client. The client is later looked up from the registry
if it's found to be missing from the transfer. If no client exists in
the registry when the transfer is resumed, it will be marked as failed.
> Keep a registry of restoration ID -> Client inside the TransferManager

- sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift
- sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift
- sdk/storage/AzureStorageBlob/Source/TransferManager.swift
- sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
This seemed to be the easiest way to do so that made the public API make sense.
Fixes #253
> Expose max concurrency in StorageBlobClient

- examples/AzureSDKDemoSwift/Source/Common.swift
- sdk/storage/AzureStorageBlob/Source/Data/Transfer.swift
- sdk/storage/AzureStorageBlob/Source/DataStructures/Enumerations.swift
- sdk/storage/AzureStorageBlob/Source/Operation/BlobDownloadOperations.swift
- sdk/storage/AzureStorageBlob/Source/Operation/BlobUploadOperations.swift
- sdk/storage/AzureStorageBlob/Source/Operation/BlockOperations.swift
- sdk/storage/AzureStorageBlob/Source/Operation/MultiBlobOperation.swift
- sdk/storage/AzureStorageBlob/Source/Operation/ResumableOperation.swift
- sdk/storage/AzureStorageBlob/Source/Operation/ResumableOperationQueue.swift
- sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
- Fixes #261. 
- Improves the `showAlert(error:)` method to print the debugDescription, if available (fixes #266).
- Fixes an issue with the `AccessTier` enum that prevented it from being properly deserialized.
There were some holes in the Operation logic. I took the opportunity to simplify ResumableOperation and ResumableOperationQueue. I would like to further shrink these, but right now, it isn't necessary.
I believe the key problem was in the BlockOperation logic. After entering a dispatch group, there were return statements that did not have a matching `group.leave()` call. As a result, these threads were lost to the ether and never able to complete. So, when the the operation was resumed, all incomplete blocks were readded to the queue but could never proceed because the original …
> UX Study Fixes.

- examples/AzureSDKDemoSwift/Source/Common.swift
- sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift
- sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift
Fixes #248.  I think the actual `EXC_BAD_ACCESS` was fixed by an earlier PR. This simply tweaks previously merged changes that caused turning the option on to yield a 400 error.
> Fix MD5 hashing and restore to true

- examples/AzureSDKDemoSwift/Source/AppDelegate.swift
- examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift
- examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift
- examples/AzureSDKDemoSwift/Source/Common.swift
- examples/AzureSDKDemoSwift/Source/CustomCells.swift
- examples/AzureSDKDemoSwift/Source/CustomTabBarController.swift
- examples/AzureSDKDemoSwift/Source/LoginViewController.swift
- sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift
- sdk/storage/AzureStorageBlob/Source/TransferManager.swift
- sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager+TransferDelegate.swift
- Simplifies client code by having the SDK invoke all completion handlers and delegate callbacks on the main DispatchQueue. 
- Restore the recommended internal labels for the `TransferDelegate` protocol based on UX study feedback.
> Perform callbacks on DispatchQueue.main

- examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift
- examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift
- sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataClass.swift
- sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataProperties.swift
Fixes #281 
The source and destination URLs on a blob transfer are the raw values
that get stored in CoreData. They aren't appropriate for a user to
consume directly, so those have been hidden and instead we add the
sourceUrl and destinationUrl properties that correctly resolve the value
if it represents a LocalURL.
> Fix BlobTransfer local URLs are unresolved

- sdk/core/AzureCore/Source/Pipeline/PipelineRequest.swift
- sdk/core/AzureCore/Tests/PipelineRequestTests.swift
It's no longer used.
We should probably file an issue to plumb through both Request and Response as `inout` parameters so they can be modified by the policies as needed, rather than needing to make a copy in order to change them.
> Remove Copyable from Request

- examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift
- sdk/core/AzureCore/Source/DataStructures/Collections.swift
- sdk/core/AzureCore/Tests/CollectionsTests.swift
- sdk/storage/AzureStorageBlob/Source/DataStructures/TransferCollection.swift
This PR:
- Fixes #303 by adding an `isExhausted` property the app developer can check.
- Wraps completion handler calls in `nextPage` and `nextItem` in appropriate calls to dispatch onto the main queue to eliminate the need for the developer to do this.
- The default behavior for "no data received" is to simply return rather than call the completion handler with `nil` data. This allows the user's app to do the right thing when the collection is exhausted without them having to manually check `isExhausted`. The property is still supplied as the app developer may want to affirmatively check this.
> PagedCollection updates

- examples/AzureSDKDemoSwift/Source/BlobDownloadViewController.swift
- examples/AzureSDKDemoSwift/Source/BlobUploadViewController.swift
- sdk/storage/AzureStorageBlob/Source/Data/AzureStorage.xcdatamodeld/AzureStorage.xcdatamodel/contents
- sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataClass.swift
- sdk/storage/AzureStorageBlob/Source/Data/BlobTransfer+CoreDataProperties.swift
- sdk/storage/AzureStorageBlob/Source/Data/Transfer.swift
- sdk/storage/AzureStorageBlob/Source/Operation/BlobDownloadOperations.swift
- sdk/storage/AzureStorageBlob/Source/Operation/BlockOperations.swift
- sdk/storage/AzureStorageBlob/Source/StorageBlobClient+Extensions.swift
- sdk/storage/AzureStorageBlob/Source/StorageBlobClientDelegate.swift
- sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift
- sdk/storage/AzureStorageBlob/Source/TransferManager.swift
- sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager+TransferDelegate.swift
- sdk/storage/AzureStorageBlob/Source/Transport/URLSessionTransferManager.swift
Closes #244.
Updates transfer manager methods to use the TransferProgress struct instead of a raw Float.
> Use TransferProgress uniformly for progress.

- Package.swift
- sdk/identity/AzureIdentity/Source/MSALCredential.swift
- sdk/storage/AzureStorageBlob/Source/StorageBlobClient.swift
This PR removes AzureIdentity from the Package.swift file. This is because we won't initially have the MSAL dependency hooked up in the shipping package so we don't need it (although we can still use it for development purposes and building out the demo app).
> Remove AzureIdentity from Package.swift.

- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- eng/pipelines/templates/stages/archetype-sdk-client.yml
Reverts #354 and avoids hard-coding the scheme so that builds can still be run on other schemes, but if no scheme is passed the build assumes that you want to build "all".
> Refactor combined pipelines

- AzureSDK.podspec
This PR adds a CocoaPods ```*.podspec``` file back into the repo. This one covers AzureCore only and we'll add more as necessary. For now this is just to facilitate some conversation and unblock various projects.
> Setup podspec

- sdk/core/AzureCore/Source/Pipeline/Policies/ContentDecodePolicy.swift
Fixes #444.
Previously, we would find content type JSON and do a round-trip deserialized/serialize loop to validate that the data was a valid JSON **object**. However, content type `application/json` is any valid JSON, not just JSON objects, which will cause this check to fail for cases within the autorest testserver since there are bodies that are valid JSON but not JSON objects.
> ContentDecodePolicy should pass through data to client

- sdk/communication/AzureCommunication/Source/Identifiers.swift
Removing the `getId()` method to align with other sdk's
> [CommunicationIdentifier] Align identifier types in Swift with other languages

- sdk/core/AzureCore/Source/Pipeline/Policies/ContentDecodePolicy.swift
* deserialize() can return non JSON format data. And the caller of deserialize() (ContentDecodePolicy on() method) will always call JSONSerialization.data() with the return value from deserialize(). And this will reult in 'Deserialization error." and the failure callback of PipelineClient will get invokded.
* We should only call  JSONSerialization.data() when the data is in JSON format. So we move the call of ' JSONSerialization.data()' inside 'deserialize()'. And we only call 'JSONSerialization.data()' when the xml data is converted into JSON format.
> Call JSONSerialization.data in deserialize() method when is JSON

- sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
- sdk/communication/AzureCommunication/Source/Authentication/CommunicationAccessToken.swift
- sdk/communication/AzureCommunication/Source/Authentication/CommunicationUserCredential.swift
- sdk/communication/AzureCommunication/Source/Authentication/JwtTokenParser.swift
- sdk/communication/AzureCommunication/Source/Authentication/ThreadSafeRefreshableAccessTokenCache.swift
- sdk/communication/AzureCommunication/Tests/CommunicationUserCredentialTests.swift
- sdk/core/AzureCore/Source/Pipeline/Policies/AuthenticationPolicy.swift
Currently, AzureCommunication depends on AzureCore's AccessToken. Chat is built in obj-c so requires an obj-c members. For chat to use AzureCommunication properly we need to create our own obj-c class access token. At the same time the Access token in Core can be changed back to a pure struct.
> [CommunicationAccessToken] Communication created version of access token 

- sdk/communication/AzureCommunication/Source/Authentication/CommunicationAccessToken.swift
token and expiresToken needs to be public so that it can be accessed from ObjC code
> Make CommunicationAccessToken members public

- sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
- sdk/core/AzureCore/Tests/Stubs/TestCallOptions.swift
- sdk/core/AzureCore/Tests/Stubs/TestClient.swift
- sdk/core/AzureCore/Tests/Stubs/TestClientOptions.swift
These mistakenly appear in the AzureCore public interface and don't need to.
> Remove test artifacts from AzureCore public interface

- CHANGELOG.md
- sdk/communication/AzureCommunication/AzureCommunication.xcodeproj/project.pbxproj
- sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenCredential.swift
- sdk/communication/AzureCommunication/Source/Authentication/CommunicationTokenRefreshOptions.swift
- sdk/communication/AzureCommunication/Tests/CommunicationTokenCredentialTests.swift
- sdk/communication/AzureCommunication/Tests/ObjCCommunicationTokenCredentialAsyncTests.m
- sdk/communication/AzureCommunication/Tests/ObjCCommunicationTokenCredentialTests.m
- sdk/communication/AzureCommunication/Tests/ObjCTokenParserTests.m
As per arch review. We want to encapsulate CommunicationUserCredential params into TokenRefreshOptions.
> [Communication] - Auth - Introducing CommunicationTokenRefreshOptions

- CHANGELOG.md
- sdk/communication/AzureCommunication/Source/Identifiers.swift
Renaming from `identifier` to `userId` in case `identifier` needs to be used for different purpose in the future. Specifically only for `MicrosoftTeamsUserIdentifier`
> [Communication] - Identifiers - Teams property renamed to userId

- AzureCommunicationChat.podspec.json
- eng/pipelines/templates/jobs/archetype-sdk-client.yml
- examples/AzureSDKSmokeTest/AzureSDKSmokeTest.xcodeproj/project.pbxproj
- examples/AzureSDKSmokeTest/Podfile
Configures the SmokeTest to pull podspecs from the build branch. This should mean that changes which would break the build can be stopped before they are introduced rather than caught after the build has been broken.
Fixes #695.
Note that I'm note entirely sure this *should* run on PRs. My original intent was only to run it for releases. I can envision a scenario where, for example, `AzureCommunication` makes a breaking change and this check will fail until `AzureCommunicationCalling` updates their SDK accordingly. Thoughts?
> Update SmokeTest for use on CI

- CHANGELOG.md
- Podfile
Workaround for:
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1280
> Pin MSAL version to avoid broken release of MSAL 1.1.16

- eng/pipelines/templates/stages/archetype-ios-release.yml
- eng/scripts/Language-Settings.ps1
- sdk/template/AzureTemplate/AzureTemplate.podspec.json
- sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj
- sdk/template/AzureTemplate/CHANGELOG.md
This PR adds ```Language-Settings.ps1``` which is used by the release tagging logic to detect artifacts that are being published by path. I've validated that this works using ```AzureTemplate```.
Closes #850
> Add tagging on release

- eng/pipelines/templates/stages/archetype-ios-release.yml
- sdk/template/AzureTemplate/AzureTemplate.podspec.json
- sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj
- sdk/template/AzureTemplate/CHANGELOG.md
This PR adds CocoaPods push support. To authenticate we are making use of the ```COCOAPODS_TRUNK_TOKEN``` environment variable which we'll pull in via a variable group (and ultimately our KeyVault). At this point I don't have the token but once that is available I'll do an end-to-end test, but the error output is what I expect at this point in time.
> CocoaPods push support

- AzureSDK.xcworkspace/contents.xcworkspacedata
- sdk/core/AzureCore/Tests/XMLModelTests.swift
- sdk/storage/AzureStorageBlob/Source/Models/StorageError.swift
- sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj
Fixes issue with `StorageError` and `MappedThing` where Xcode can no longer automatically synthesize these coding keys.
Also cleans up some other project files.
> Fix build issues with enum CodingKeys

- eng/pipelines/templates/stages/archetype-ios-release.yml
- eng/scripts/Publish-SwiftPackage.ps1
- sdk/communication/ci.yml
- sdk/core/ci.yml
- sdk/identity/ci.yml
- sdk/storage/ci.yml
- sdk/template/AzureTemplate/AzureTemplate.podspec.json
- sdk/template/AzureTemplate/AzureTemplate.xcodeproj/project.pbxproj
- sdk/template/ci.yml
An initial pass at publishing SPM packages via the release pipeline. It requires that we add a repository resource (or two) to each individual pipeline. Then during this job we clone the mono-repo, and the ```SwiftPM-[packagename]``` repo. We then checkout an orphan branch and copy the files over, commit, tag and then push (tag only).
In cases where a package doesn't support SPM (e.g. ```AzureCommunicationCalling```), we just don't emit that job.
> Add SPM publishing to release pipeline

- examples/AzureSDKSmokeTest/AzureSDKSmokeTest/AppDelegate.swift
- examples/AzureSDKSmokeTest/Podfile
- jazzy/AzureCommunicationChat.yml
- sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
- sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
- sdk/communication/AzureCommunicationChat/CHANGELOG.md
- sdk/communication/AzureCommunicationChat/README.md
Bumps AzureCore dependency to 1.0.0-beta.12 for compatibility withe the latest version of AzureCommunicationCalling.
> Release AzureCommunicationChat 1.0.0-beta.12

- eng/pipelines/templates/stages/archetype-ios-release.yml
Queuing release pipelines for Azure Communication is failing because the the release stage YAML incorrectly references ```safeName``` for the stage name. Unfortunately this value isn't present and so in pipelines with more than one artifact, the release stage names end up being duplicated in the resulting YAML which is an error. This should fix that up.
> Fix duplication release stage name

- eng/pipelines/templates/stages/archetype-ios-release.yml
This PR fixes the broken communications release pipeline. It was breaking because even though the release stage for SPM was behind a condition, the YAML itself was still invalid (the ```checkout:```). To fix it I moved to using a template ```{{if ...}}``` condition which omits the entire job from the generated YAML.
> Fix communications release pipeline

- Podfile
- sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
- sdk/communication/AzureCommunicationChat/Tests/ChatClientDVRTests.swift
- sdk/test/AzureTest/AzureTest.xcodeproj/project.pbxproj
- sdk/test/AzureTest/Package.swift
By pointing to our fork, we can iterate more quickly on issues that arise with DVR.
> Update DVR references to point to fork rather than venmo

- sdk/communication/AzureCommunicationChat/Tests/test-settings.plist
This was caused, as best I can tell, by a blank environment variable key/value in the AzureCommunicationChat scheme. Removing this empty variable fixed the issue for me.
> Fix (os/kern) invalid host bug

- Podfile
- sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
- sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/xcshareddata/xcschemes/AzureCommunicationChat.xcscheme
- sdk/communication/AzureCommunicationChat/Tests/Recordings/test_CreateThread_WithoutParticipants.json
- sdk/communication/AzureCommunicationChat/Tests/Recordings/test_ListThreads_ReturnsChatThreadItems.json
- sdk/test/AzureTest/DVRSessionTransport.swift
Uses the `filterHeaders` property of DVR to remove authorization headers, which permits us to commit the Chat test recordings.
DVR still needs to be updated to that header filters are done in a case insensitive way.
> Scrub headings and commit chat test recordings.

- README.md
@tjprescott Just to confirm will this also update the landing page of CocoaPods?
https://cocoapods.org/pods/AzureCommunicationChat
> Remove Chat (and Calling and Common) from list of libraries in beta

- sdk/communication/AzureCommunicationChat/CHANGELOG.md
- sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
- sdk/communication/AzureCommunicationChat/Source/Signaling/CommunicationSignalingClient.swift
- applicationId should be empty by default instead of the bundle identifier
- add missing trouter call to set activity state
> ChatClient set default applicationId to empty string + add missing signaling init step

- sdk/communication/test-resources.json
This will allow the python script to run immediately after the template deployment, as intended.
> Restore test-resources.json

- examples/AzureSDKDemoSwift/AzureSDKDemoSwift.xcodeproj/project.pbxproj
- sdk/communication/AzureCommunicationChat/AzureCommunicationChat.xcodeproj/project.pbxproj
- sdk/communication/AzureCommunicationChat/Source/ChatClient.swift
- sdk/communication/AzureCommunicationChat/Source/Signaling/Events/ChatEvent.swift
- sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterNotificationPayload.swift
- sdk/communication/AzureCommunicationChat/Tests/TrouterEventUtilTests.swift
- The version of notification payloads in preview6 uses recipientMri instead of recipientId
- Fix null metadata check to look for "null" instead of empty string
- Update payload unit tests
> Update GA patch for preview6

- sdk/core/AzureCore/CHANGELOG.md
- sdk/core/AzureCore/Source/Pipeline/Transport/URLSessionTransport.swift
- sdk/test/AzureTest/Source/DVRSessionTransport.swift
Fixes for AzureCore and AzureTest to prevent a callback fallthrough in the event of a bad status code. Also adds other fixes needed by Chat until more permanent measures can be implemented.
> [AzureCore] Fix transport callback fallthrough

- sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
- sdk/communication/AzureCommunicationCommon/Tests/ObjCCommunicationTokenCredentialAsyncTests.m
- sdk/communication/AzureCommunicationCommon/Tests/ObjCCommunicationTokenCredentialTests.m
Removing an old reference to AzureCore in the Common Project. 
Common should not have any dependency on Core.
> [Project] Remove Core framework linking

- sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json
- sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
- sdk/communication/AzureCommunicationCommon/CHANGELOG.md
- Fixed the logic of `PhoneNumberIdentifier` to always maintain the original phone number string whether it included the leading + sign or not.
> A patch release for AzureCommunicationCommon 1.1.1

- sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/xcshareddata/xcschemes/AzureCommunicationCommon.xcscheme
- sdk/communication/AzureCommunicationCommon/Tests/ObjCCommunicationTokenCredentialAsyncTests.m
- sdk/communication/AzureCommunicationCommon/Tests/ObjCCommunicationTokenCredentialTests.m
The three test that are disabled runs properly locally, but during the pipeline run sometimes they fail which is the known issue. I am disabling these tests untill we will change the token autorefreshing logic and update the tests regarding the new logic. The ADO already created for it -> [User Story 3051451](https://skype.visualstudio.com/SPOOL/_workitems/edit/3051451): [SDK][Common][iOS] Add a backoff mechanism for the CommunicationTokenCredential
> Disabled flaky tests of the AzureCommunicationCommon

- sdk/core/AzureCore/CHANGELOG.md
- sdk/core/AzureCore/Source/DataStructures/Collections.swift
- sdk/core/AzureCore/Tests/CollectionsTests.swift
With swift `async/await` available in more recent versions of iOS, we can benefit from async wrappers at the core level in other components.
This PR introduces minimal functionality to address async paging of results.
> [Feature] Provide async wrappers for PagedCollection

- eng/CHECKENFORCER
This is no longer necessary with [check enforcer v2](https://aka.ms/azsdk/checkenforcer)
> Remove CHECKENFORCER file

- jazzy/AzureCommunicationCommon.yml
- sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json
- sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
- sdk/communication/AzureCommunicationCommon/CHANGELOG.md
Release of the following updates:
- [[iOS] Added support for MicrosoftBotIdentifier](https://github.com/Azure/azure-sdk-for-ios/commit/e1de57197809c8a19fb43399343bfb4dcab354c3)
- [Introducing a public cancel API for the CommunicationTokenCredential](https://github.com/Azure/azure-sdk-for-ios/commit/1e7b2a6758cd354a57abbc79e5c092ae0f802cb4)
- [Added a backoff mechanism for the CommunicationTokenCredential for au…](https://github.com/Azure/azure-sdk-for-ios/commit/9ab726d216976f27f609786eee2d4113c9048aa6)
> [ios] AzureCommunicationCommon 1.2.0-beta.1 release

- eng/pipelines/templates/stages/archetype-ios-release.yml
Internal Azure SDK Engineering System update of the used Ubuntu image per
- https://github.com/Azure/azure-sdk-tools/issues/5472
To determine this change, I searched for all Ubuntu 18 strings as explained in [#5472](https://github.com/Azure/azure-sdk-tools/issues/5472).
> Update from machine pools from Ubuntu 18.04 to Ubuntu 20.04

- sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
- sdk/core/AzureCore/AzureCore.xcodeproj/project.pbxproj
The build scripts within the Xcode projects do not support paths with spaces and will fail. 
This PR updates the projects to support this situation
> Support spaces in the build scripts

- sdk/communication/AzureCommunicationChat/Source/Signaling/TrouterSettings.swift
- sdk/communication/AzureCommunicationChat/Tests/TestSettings.swift
- sdk/communication/AzureCommunicationChat/Tests/TrouterSettingsUnitTest.swift
We've updated the Trouter endpoints for EU or non-EU based on whether the resource location is in the EUDB countries or not: ["europe", "france", "germany", "norway", "switzerland", "sweden"]
- if EU: https://go-eu.trouter.teams.microsoft.com/v4/a
- if non-EU: https://go.trouter.teams.microsoft.com/v4/a
We've also updated the registrar endpoint to the following: https://teams.microsoft.com/registrar/prod/v3/registrations
> Add EUDB Compliant Support for AzureCommunicationChat

- sdk/communication/AzureCommunicationChat/Source/NotificationUtils/IdentityUtil.swift
- sdk/communication/AzureCommunicationChat/Source/Serializer/IdentifierSerializer.swift
`.cloudEnvironment` was being introduced in AzureCommunicationCommon version `1.2.0-beta.1`. This PR reverts the reference back to `.cloudEnviroment` since AzureCommunicationChat still references AzureCommunicationCommon version `~> 1.0`. This resolves the following error in our release pipeline:
> \- ERROR | xcodebuild:  AzureCommunicationChat/sdk/communication/AzureCommunicationChat/Source/Serializer/IdentifierSerializer.swift:126:30: error: value of type 'MicrosoftTeamsUserIdentifier' has no member 'cloudEnvironment'
> [Communication][Chat] Revert reference on .cloudEnvironment to its previous name

- .github/CODEOWNERS
sdk/storage was removed from the repository with this [PR](https://github.com/Azure/azure-sdk-for-ios/pull/1336) on Aug 16th, 2022 but the entry wasn't.
> Remove the invalid path entry sdk/storage entry from CODEOWNERS

- sdk/core/AzureCore/Source/Util/ApplicationUtil.swift
https://github.com/Azure/azure-sdk-for-ios/issues/1672
Use of @available(iOSApplicationExtension, unavailable) for Xcode 14 and 15
> Fix [BUG] https://github.com/Azure/azure-sdk-for-ios/issues/1672

- jazzy/AzureCommunicationCommon.yml
- sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json
- sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
- sdk/communication/AzureCommunicationCommon/CHANGELOG.md
Added support for a new communication identifier `MicrosoftTeamsAppIdentifier`. It will impact any code that previously depended on the use of `UnknownIdentifier` with rawIDs starting with `28:orgid:`, `28:dod:`, or `28:gcch:`.
> GA release for AzureCommunicationCommon 1.2.0

- sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json
- sdk/communication/AzureCommunicationChat/CHANGELOG.md
This PR is used to update AzureCommunicationCommon Package to 1.2.0.
All existing functionalities, including real-time notification and push notification, work well after the change.
> Update Common Package Version

- eng/common/pipelines/templates/steps/save-package-properties.yml
- eng/common/scripts/Generate-PR-Diff.ps1
- eng/common/scripts/Package-Properties.ps1
This reverts commit f7291906a46ee5159a7bdf3f543c916bf3e7b5ae.
Reverting, merged too soon and have to make updates.
> Revert "Filter out Excludes for PR Pipelines (#1982)"

- eng/common/pipelines/templates/steps/save-package-properties.yml
- eng/common/scripts/Generate-PR-Diff.ps1
- eng/common/scripts/Package-Properties.ps1
Sync eng/common directory with azure-sdk-tools for PR https://github.com/Azure/azure-sdk-tools/pull/9649  See [eng/common workflow](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/README.md#workflow)
> Sync eng/common filter out excludes for pr pipelines 9649

- jazzy/AzureCommunicationCommon.yml
- sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json
- sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.xcodeproj/project.pbxproj
- sdk/communication/AzureCommunicationCommon/CHANGELOG.md
- sdk/communication/AzureCommunicationCommon/README.md
This PR includes the following changes:
* Release updates for AzureCommunicationCommon 1.3.0
* The TeamsExtensionUserIdentifier and PhoneNumberIdentifier changes will be released
> Release updates for AzureCommunicationCommon 1.3.0
